### ISSUE TITLE
I am wondering how to integrate this template with dashboard

### ISSUE THREAD

**Issue by LinYKen** [creativetimofficial/argon-design-system-react#1]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by einazare** [comment]
Hello there, @LinYKen ,

Thank you for your interest in working with our products.
You just need to copy and paste what you want in your project.
In a few days, I'll try and make a tutorial for this issue.

Best,
Manu

**Comment by LinYKen** [comment]
Thx, I attempted for several times, finally gave up. Too much issues popped up, waiting for your tutorial

**Comment by einazare** [comment]
Hello again, @LinYKen ,

You could also ask for help on StackOverflow.
I've seen a lot of people asking for help there about our products, for different purposes, integrating kits with dashboards, integrating our products with other technologies, etc.

Best,
Manu

**Comment by LinYKen** [comment]
hey If u release the tutorial, where can I  get it? On the github or your official website?

**Comment by einazare** [comment]
Hello again, @LinYKen ,

I am not sure where I am going to publish it, it really depends on the Creative Tim Board and my manager. When I'll publish it, I'll put a link here.

Best,
Manu
