### ISSUE TITLE
scss var in compiled css

### ISSUE THREAD

**Issue by Dolu89** [creativetimofficial/argon-design-system-react#10]
Hello,

I have a problem on `npm run build` because there is some var in compiled css
Did I miss something ?
Anyway, I used sass to compile scss files.

https://github.com/creativetimofficial/argon-design-system-react/blob/0a4ea7e7817fb84f7f0256f1bce7b5d56e25592a/src/assets/css/argon-design-system-react.css#L12463

Thanks for this awesome design anyway!

**Comment by einazare** [comment]
Hello there, @Dolu89 ,

I am not sure why this happens.
I've tried to fix it, but without any prevail, any guidance will be much appreciated.

Best,
Manu

**Comment by ihatem** [comment]
I had the same issue, looks like `argon-design-system-react.scss` file is pointing to the wrong paths. 

I update the paths manually, it works but it's not viable with node_modules updates. 

Here's the `scss` file updated: 
```diff
 // Bootstrap Functions
-@import "../../../node_modules/bootstrap/scss/functions";
+@import "bootstrap/scss/_functions.scss";

 // Theme Variables
-@import "argon-design-system/variables";
+@import "./argon-design-system/variables";

 // Bootstrap Core
-@import "../../../node_modules/bootstrap/scss/bootstrap";
+@import "bootstrap/scss/bootstrap";

 // Theme Core
-@import "argon-design-system/theme";
+@import "./argon-design-system/theme";

 // React Differences
-@import "react/react-differences";
+@import "./react/react-differences";
```

PR is needed
