### ISSUE TITLE
Production build not running

### ISSUE THREAD

**Issue by Blackwatch1910** [creativetimofficial/argon-design-system-react#12]
### Version
1.1.0
### Reproduction link
https://www.dropbox.com/sh/85zrtorfmsj3hwu/AACpgIOxyFxfYvTHD3uWjsZMa?dl=0
### Operating System
windows 10
### Device
Acer aspire 5
### Browser & Version
Brave 1.7
### Steps to reproduce
1.github.com/Blackwatch1910/vysion
2.Download above code and run "npm run build"
3.deploy the build version.
4. The deployed site won't run.

### What is expected?
The deployed site should render the page as in 'localhost/landing-page' on local machine
### What is actually happening?
Nothing actually shows up.

---
### Solution
tried configuring "homepage" attribute but didn't work.

**Comment by einazare** [comment]
Hello there, @Blackwatch1910 ,

Please delete the homepage prop from inside the package.json file.

Best,
Manu

**Comment by Blackwatch1910** [comment]
Worked. Thanks a lot @EINazare.
