### ISSUE TITLE
Navbar Break Points - Disappearing Elements at Certain Widths

### ISSUE THREAD

**Issue by ml-johnson** [creativetimofficial/argon-design-system-react#16]
### Version
1.1.0
### Reproduction link
https://github.com/mj1268/ArgonBugReport-NavbarCollapse
### Operating System
Windows 10
### Device
Laptop
### Browser & Version
Google Chrome Version 81.0.4044.138 (Official Build) (64-bit)
### Steps to reproduce
1. Adjust width of window
2. When adjusting past each breakpoint, observe when the NavItems disappear/reappear - independent of the appearance of the collapsed toggle hamburger menu
### What is expected?
Expect elements of Navbar to be swapped out with the toggle menu as the screen size passes the specified breakpoint (elements disappear, toggle menu simultaneously appears at the same screen width).
### What is actually happening?
1. Elements of the Navbar are disappearing after certain breakpoints, but before the toggle menu appears, leading to no visible navigational items in certain screen widths.

---
### Additional comments
This is my first time submitting a bug report, please let me know if there's any other info you need.  Thanks!

**Comment by einazare** [comment]
Hello there, @mj1268 ,

It seems to me that the product is working just fine.
Could you please share with us a video with your issue?

Best,
Manu

**Comment by ml-johnson** [comment]
Okay, I actually was unable to replicate it myself.  😆

I think it was a build issue on my end somewhere along the way, I reinstalled the npm modules from scratch and it started working.

Sorry, thanks!
