### ISSUE TITLE
[Bug] Closing the menu from colapsed Navbar seems laggy

### ISSUE THREAD

**Issue by iamf3i** [creativetimofficial/argon-design-system-react#2]
### Version
1.0.0
### Reproduction link
https://demos.creative-tim.com/argon-design-system-react/#/
### Steps to reproduce
1. Get the collapsed Navbar by reducing the window width
2. Open the menu Toggler
3. Close it.

The behaviour is different from other Ui kit (BLK, non react Argon, Angular Argon....)
### What is expected?
Instant closing of the menu
### What is actually happening?
Delay, seems laggy.

---
### Additional comments
I'm kinda newbie but is it a css issue ? Transition ? What should I try to fix it ?

**Comment by einazare** [comment]
Hello there, @iamf3i ,

Thank you for your interest in working with our products and for using our issue template.
At the moment we do not have a fix for this issue.
We'll continue to search for one.
Meantime, if you have a solution, please share it with us.

Best,
Manu

**Comment by iamf3i** [comment]
The issue is related to the uncontrolled collapse component from reactstrap.
It automatically adds the "show" css class which is used to describe the animation for opening.

BUT

It doesn't add automatically the "collapsing-out" for the closing animation.

Implementing the Collapse component instead of Uncontrolled Collapse will allow us to describe the actions for the onExiting event, and put the "collapsing-out" animation to the component.

Is it worth a pull request ?

Rgds,

Fawzi

**Comment by einazare** [comment]
Hello there, @iamf3i ,

You can open a PR, but it would be great if you would open it on another branch, not on the master one, but on the v1.1.0 branch.

Best,
Manu
