### ISSUE TITLE
Headroom.JS doesn't work with Next.JS

### ISSUE THREAD

**Issue by souzajr** [creativetimofficial/argon-design-system-react#3]
I'm using Next.JS and Headroom.JS just doesn't work (ReferenceError: document is not defined). Any solution?

**Comment by einazare** [comment]
Hello there, @souzajr ,

Thank you for your interest in working with our products.
It seems that you haven't respected our ISSUE_TEMPLATE, so we are going to close it.
Please add a new comment here, or open a new issue, by filling the mentioned ISSUE_TEMPLATE and please be sure that your issue title is a very small description of your issue as well.
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/argon-design-system-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->
```

All the best,
Manu
Developer @ [Creative-Tim.com](http://creative-tim.com/)
