### ISSUE TITLE
[Feature Request] Add TypeScript typings for argon-design-system-react package

### ISSUE THREAD

**Issue by rjkz808** [creativetimofficial/argon-design-system-react#5]
### What is your enhancement?
This UI kit is awesome. But it could be even better if there's some possibility to integrate with TypeScript. A lot of React projects use TS and also a lot of react component libraries have their own types declaration files (for example, https://github.com/react-bootstrap/react-bootstrap and https://github.com/mui-org/material-ui).

**Comment by einazare** [comment]
Hello there, @rjkz808 ,

I've just made a new branch called feature/typescript-support: https://github.com/creativetimofficial/argon-design-system-react/tree/feature/typescript-support
If you want, you can create a PR there, but you will have to keep the actual code base, i.e., the project should work with Babel as well as TypeScript.
Also, the commits should follow the Angular Contribution Guide: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines

Best,
Manu

**Comment by rjkz808** [comment]
I understand it. Regular declaration files would only affect projects that use TypeScript, I'll not rewrite the whole code base to TS 😄

**Comment by rjkz808** [comment]
Oh, I think I missed up the library source code. I thought you have your own React components, but now I understand that it's more like an UI theme for Bootstrap. So, it can be used with any React libraries that are integrated with bootstrap (like react-bootstrap or reactstrap), right?

**Comment by rjkz808** [comment]
And this repo is an example of using this theme, isn't it?

**Comment by einazare** [comment]
Hello again, @rjkz808 ,

I do not follow your comments, especially the last one, which theme are you referring to and which repo?

Best,
Manu

**Comment by rjkz808** [comment]
As I understand this repo is a showcase for your Bootstrap CSS theme (which I hope is placed here https://github.com/creativetimofficial/argon-design-system-react/blob/master/src/assets/css/argon-design-system-react.css). I thought that `Argon Design System React` heading means that you have your own react components library with this styling.

**Comment by rjkz808** [comment]
> As I understand this repo is a showcase for your Bootstrap CSS theme (which I hope is placed here https://github.com/creativetimofficial/argon-design-system-react/blob/master/src/assets/css/argon-design-system-react.css). I thought that `Argon Design System React` heading means that you have your own react components library with this styling.

Or maybe it's not a showcase project but a template one

**Comment by einazare** [comment]
Hello again,

This is a Bootstrap Template: https://demos.creative-tim.com/argon-design-system-react/?ref=adsr-github-readme#/

Best,
Manu

**Comment by rjkz808** [comment]
Yup, and this repo is its source code, right?

**Comment by rjkz808** [comment]
I mean you don't have your own react components library, but you have some template/showcase repos of your CSS library and one of them is for React. Is it correct?

**Comment by einazare** [comment]
Yes, indeed.
Please note, that our CSS library, is actually a theme over Bootstrap (or other libraries, such as Tailwindcss, Material-UI, Vuetify, etc.).
